### ISSUE TITLE
Huge Lag Spikes With Vault Hunters

### ISSUE THREAD

**Issue by Starblze** [Iskallia/Vault-public#746]
**Describe the bug**
The game lags every 15 seconds or so, usually for a total of 3 seconds with the game completely frozen. I've allocated 4 gb of ram, then 6 gb of ram, then 8 gb of ram. I've tried using optifine, sodium ports for forge, roadrunner, and other fps boosting mods, on their own and with each other. Nothing fixes the problems, I have recommended settings, with 0 mipmap, 0 biome blend, fast graphics, low render distance. I have tried basically everything, and the game is still completely unplayable. The only thing that fixes it is setting render distance to 1 (with special sodium settings) but that makes the game unplayable as you can't see anything. I've tried both curseforge and multimc with all these settings

**To Reproduce**
1. Load vault hunters 
2. Load singleplayer world
3. Try to play with lagspikes

**Expected behavior**
I expect to play modded minecraft with little to no lagspikes, as I have done in many other modpacks. Unfortunately, this did not happen.

**Info (please complete the following information):**
- Single Player World
- All vault versions

**Additional context**
11th gen Intel Processor, 16 gb ram processor, intel iris xe graphics with 2 gb ram.

**Comment by marho13** [comment]
I had the same issue when running it 16GB ram, once every 10 seconds I have a 2 sec spike.
My computer is a water-cooled, Threadripper 1950x, and GTX 1080.

I rarely have these sort of issues on other mod packs 🤷

**Comment by Ithkamakazi** [comment]
there could be some background programs running on you pc that's eating up the ram, also no other mobs besides optifine? i know that was at the very lease worked with as that's what Iskall does use

**Comment by Starblze** [comment]
> there could be some background programs running on you pc that's eating up the ram, also no other mobs besides optifine? i know that was at the very lease worked with as that's what Iskall does use

sorry it took so long to respond lol, I've tried many combinations of mods besides optifine, including roadrunner, sodium ports for forge, e.t.c. or just optifine, plus the original vault hunters with no fps boosters, also background programs aren't eating up ram, the only things I have on it are system, file explorer, e.t.c. checked this already

**Comment by Starblze** [comment]
dang it I accidentally closed lol, 

> I had the same issue when running it 16GB ram, once every 10 seconds I have a 2 sec spike. My computer is a water-cooled, Threadripper 1950x, and GTX 1080.
> 
> I rarely have these sort of issues on other mod packs 🤷

I've tried different amounts of ram as well lol, pretty decent pc too so Idk why this is happening, this would be super useful if someone could figure this out, maybe figure out if a specific mod is causing it or something

**Comment by Starblze** [comment]
Ok with further experimenting I have figured out a few things (have yet to try removing different mods in the modpack). The further you go towards y level 0, the more common the lagspikes become and the worse they get, when you break blocks in the nether or overworld, that seems to cause one, occasionally placing blocks also causes it. loading chunks can cause it, and moving entities also caused it. Now I just need to figure out which mods are doing it, any help would be appreciated.

**Comment by Premieress** [comment]
I just run around one zone, chunk has been loaded for about 10 minutes already and I get the lag spikes. Not doing anything but running around. I've played on other large modpacks and haven't had this issue so I'm sure it is just one mod causing the issue. Unfortunately I am not knowledgeable about how to figure out which mod it is.

**Comment by Cowio** [comment]
Hello fellow Vault-Hunter.

I had same issue this friday afternoon. I fixed it fairly easily by switching my Java version from jre1.8.0_301 to jdk-17. I do not know how or why, but it seems that the Java version is causing the CPU to spike and making the game freeze for 1-3 seconds. Hope it helps. Also do you mind posting your current Java version for debugging which Java versions does not work in the case of the lag problem?

- Cowio

**Comment by Premieress** [comment]
Tbh I have no idea how to check that and switch it. I will try to google how and get back to you if I figure it out.

**Comment by Premieress** [comment]
1.8.0_321-b07 is the build number.

**Comment by Cowio** [comment]
Okay simply try and uninstall Java from your PC, then install a newer Java version like the Java 17. You can always check which Java version your PC is running on by doing the following:

Windows Start
Open Command Prompt
Type the following command line: "java -version"

- Cowio

**Comment by Starblze** [comment]
> 

Great! Thank you for your comment, this fixed the problem for me mostly, although if I head to low y levels (like in caves or mining) the problem persists, again, same setup as before but using java 17. This solution improves playability to mostly playable, although there are still the problems of low y levels. Any advice on fixing that?

**Comment by Cowio** [comment]
Happy to help. I only stated my knowledge in how older versions of Java seems to lag out Minecraft. But if I were to guess the hardware in your PC (the graphics card), could be cause the lag, as of the low y-level stuff, I have no idea. You could try and send me your world file and I could check if it is your world or simply your installed hardware. Another thing to try, which may seem a little wierd, but try to store every item you have in your inventory in a chest and see if it continues to lag on the low y-levels. Also try with optifine, that should help on the fps.

- Cowio

**Comment by Starblze** [comment]
I was testing around quite a bit to figure out what was causing the lag, and then it just stopped! I'm closing this issue, to anyone who has the same problem as me, please try changing your java version.
